-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: name-tests-test
